name: Lint & Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
  GOOGLE_SHEETS_ID: ${{ secrets.GOOGLE_SHEETS_ID }}
  KV_REST_API_READ_ONLY_TOKEN: ${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}
  KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
  KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
  KV_URL: ${{ secrets.KV_URL }}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters and check build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm i --force

      - name: Run linters
        run: npm run lint

      - name: Run build
        run: npm run build

        